export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_ERROR = 'GET_POSTS_ERROR';

export const SAVE_POSTS_SUCCESS = 'SAVE_POSTS_SUCCESS';
export const SAVE_POSTS_ERROR = 'SAVE_POSTS_ERROR';