export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_ERROR = 'GET_POSTS_ERROR';

export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_ERROR = 'FETCH_POST_ERROR';

export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';

export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';

export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';

export const FETCH_USER_POSTS_SUCCESS = 'FETCH_USER_POSTS_SUCCESS';
export const FETCH_USER_POSTS_ERROR = 'FETCH_USER_POSTS_ERROR';

export const SAVE_USER_POST_SUCCESS = 'SAVE_USER_POST_SUCCESS';
export const SAVE_USER_POST_ERROR = 'SAVE_USER_POST_ERROR';

export const EDIT_USER_POST_SUCCESS = 'EDIT_USER_POST_SUCCESS';
export const EDIT_USER_POST_ERROR = 'EDIT_USER_POST_ERROR';

export const DELETE_USER_POST_SUCCESS = 'DELETE_USER_POST_SUCCESS';
export const DELETE_USER_POST_ERROR = 'DELETE_USER_POST_ERROR';